version: '3.8'

services: 
  frontend:
    container_name: team-builder-pk-frontend
    build: ./frontend
    ports:
      - "8080:80"
    restart: unless-stopped

  backend:
    container_name: team-builder-pk-backend
    build: ./backend
    depends_on:
      - postgres
    ports:
      - "8081:8081"
    restart: unless-stopped

  postgres:
    container_name: team-builder-pk-postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=pk_db
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes: 
      - ./data:/var/lib/postgresql/data
    restart: unless-stopped